# base.exp_name / model.type / model.ckpt_path 3개만 작성

base:
  save_path: /nas2/checkpoints/janus_dpo_rebuttal/eval
  exp_name: 0128_iter3_1e6_beta5_simpo05_sft4/ckpt_900
  task_name: t2icompbench

  world_size: 2
  precision: bf16 

model:
  type: pl # * official / pl 
  ckpt_path: /nas2/checkpoints/janus_dpo_rebuttal/ckpt/iter3/0128_iter3_1e6_beta5_simpo05_sft4/version_0/step=000900.ckpt
  # ckpt_path: /nas2/checkpoints/janus_dpo_rebuttal/ckpt/iter3/0128_iter3_1e6_beta5_simpo05_sft2/version_0/step=000380.ckpt
  # model_path: /nas2/checkpoints/janus_dpo_rebuttal/iter1_hf_ckpt # 7B base
  model_path: /nas2/checkpoints/janus_dpo_rebuttal/iter2_hf_ckpt
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2

task:
  # 고정
  num_workers: 4
  seed: [42] # [5,6,7,8,9]
  parallel_size: 1 
  temperature: 1
  cfg_weight: 5
  data_path: /nas/backup/data/visual_llama_eval/T2I-CompBench_dataset
  
  # 비고정
  batch_size: 8 # maybe, optimal
  split: val # train/val/미지정
  category: ["non-spatial", "complex", "color", "3d_spatial", "spatial", "texture", "shape", "numeracy"] # ["shape", "spatial", "color", "texture", "3d_spatial", "numeracy", "complex", "non-spatial"]
  s_idx:
  e_idx:

  eval:
    # 카테고리의 상위
    img_dir:
    np_num: 8 # 고정 
    complex_only: False # 고정
