# Step 3-1. Compositional VQA

seed: 42
world_size: 6
batch_size: 32 # attribute, layout
# batch_size: 24 # non-spatial, complex
num_workers: 4

data_path: /nas2/data/Janus_dataset/next_v2/appendix/iter2/data/prompt/base_prompt_20005.json
s_idx: 
e_idx: 


image_path: ./examples/step2/images # not required in VQA Question
img_constraint:

save_path: /nas2/data/Janus_dataset/next_v2/appendix/iter2/data/prompt/step3
save_name: vqa_question
prompt_type: qs


# iter1 ckpt
ckpt_path:
model:
  model_path: /nas2/data/Janus_dataset/next_v2/appendix/ospo_iter1_nas/hf_ckpt # 7B base
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2


generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 256