# Step 2-1. Negative / Dense Prompt Generation

seed_list: [0,1,2]
world_size: 6
# batch_size: 24 # attribute, layout
batch_size: 12   # non-spatial
# batch_size: 10   # complex
num_workers: 4

# = negative prompt
# data_path: /nas2/data/Janus_dataset/next_v2/appendix/iter2/data/prompt/step2/negative_prompt_0_12000.json
data_path: /nas2/data/Janus_dataset/next_v2/appendix/iter2/data/prompt/step2/negative_prompt_12000_end.json
s_idx: 
e_idx: 

prompt_type: dense
save_path: /nas2/data/Janus_dataset/next_v2/appendix/iter2/data/prompt/step2
# save_name: dense_prompt_0_12000
save_name: dense_prompt_12000_end

# iter1 ckpt
ckpt_path:
model:
  model_path: /nas2/data/Janus_dataset/next_v2/appendix/ospo_iter1_nas/hf_ckpt # 7B base
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2

generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.0 # 1.2
  top_p: 0.9
  max_new_tokens: 512