# Step 4. Training

base:
  save_path: ./checkpoints/logs
  exp_name: 
  world_size: 4
  resume: 


model:
  model_path: ./checkpoints/Janus-Pro-7B
  cache_dir: ./checkpoints/hf_cache
  flash_attn: True


use_peft: True 
lora:
  lora_rank: 32
  lora_alpha: 64
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]
  modules_to_save: # Keeps selected layers trainable without applying LoRA.


dataset:
  train:
    batch_size: 8 # [WARNING] When train in copo_mode=True, use less batch size than when the copo_mode=False 
    num_workers: 4
    data_path: ./examples/train.json
    num_samples:              
  val:
    batch_size: 4 # A100; max 8 because of DPGBench (long prompt)
    num_workers: 4
    # 0.vqa | 1.general | 2.hn-image-id | 3.hn-image-ood | 4.hn-text-id | 5.hn-text-ood
    data_path: 
      task_0: validation/val_vqa.json
      task_1: ./examples/val.json
      task_2: validation/val_hn_id.json
      task_3: validation/val_hn_ood.json
      task_4: validation/val_hn_text_id.json
      task_5: validation/val_hn_text_ood.json
    temperature: 1.0
    cfg_weight: 5.0


optimizer:
  init_lr: 1e-5 
  betas: [0.9, 0.95]
  weight_decay: 0.00 
  eps: 1e-8 
  scheduler_type: constant # cosine
  min_lr: 1e-6 


experiment:
  seed: 42
  precision: bf16 # 32 / bf16
  warmup_ratio: 0.0
  gradient_clip_val: 1.0
  enable_checkpointing: True
  gradient_checkpointing: True 
  gradient_accumulation_steps: 4
  max_training_steps: 500
  save_steps: 
  log_steps: 5
  val_steps: 50 
  log_by_category: False

  freeze:
    vision_model: True
    aligner: True
    gen_vision_model: True
    gen_aligner: True
    gen_head: True
    gen_embed: True
    language_model: False

tokenizer:
  max_length: 2048
  max_prompt_length: 1024
  truncation_mode: keep_end 
  truncation_side: left 
  label_pad_token_id: -100  

algo: 
  beta_1: 3
  beta_2: 5 # copo
  gamma_beta_ratio_1: 0.5 
  gamma_beta_ratio_2: 0.5

  label_smoothing: 0.0 
  loss_type: sigmoid

  # loss weight 
  simpo_weight: 0.8
  sft_weight: 1.5 
  copo_weight: 0.5 # copo_weight > 0.0, automatically set mdpo_mode=True 

  # reward clipping weight
  simpo_clipping_weight: 0.0
  copo_clipping_weight: 0.0

