# Step 4. Decompositional VQA

seed: 0
world_size: 4
batch_size: # set according to category and GPU memory
num_workers: 4

data_path: ./prompt/base_prompt.json # ./prompt/vqa_question.json
s_idx:
e_idx: 

prompt_type: question # answer
image_path: ./images # not required in generating questions (only for generating answers)
save_path: ./prompt
save_name: vqa_question # vqa_result

ckpt_path: 
model:
  model_path: ./checkpoints/Janus-Pro-7B # deepseek-ai/Janus-Pro-7B
  cache_dir: ./checkpoints/hf_cache
  attn_mode: flash_attention_2

generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 256