# Step 3-1. Compositional VQA

seed: 42
world_size: 4
batch_size: 32 # attribute, layout
# batch_size: 4 # non-spatial
# batch_size: 8 # complex
num_workers: 4

# vqa question prompt
# data_path: /nas2/data/Janus_dataset/next_v2/numeracy_add/vqa_question_5k.json
data_path: /nas2/data/Janus_dataset/next_v2/numeracy_add/vqa_question_6k.json
s_idx: 
e_idx:

img_constraint: 
# image_path: /nas2/data/Janus_dataset/main_exp/aaai/janus/numeracy_add_5k
image_path: /nas2/data/Janus_dataset/main_exp/aaai/janus/numeracy_add_6k
save_path: /nas2/data/Janus_dataset/next_v2/numeracy_add
save_name: vqa_result_6k


# iter1 ckpt
ckpt_path: 
model:
  model_path: /nas2/checkpoints/Janus-Pro-7B # deepseek-ai/Janus-Pro-1B
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2


generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 256