# Step 3-1. Compositional VQA

seed: 0 # 42
world_size: 1
# batch_size: 12 # 32 # attribute, layout
# batch_size: 4  # 8 # non-spatial
batch_size: 8 # complex
num_workers: 4


# vqa question prompt
prompt_type: ans
data_path: /nas2/checkpoints/janus_dpo_rebuttal/data/iter3/data/prompt/step3/vqa_question.json
# s_idx: 14000
# e_idx: 18000

# 앨리스에서 진행
# s_idx: 18000
# e_idx: 21000

s_idx: 23000
e_idx: 25000

img_constraint: 
image_path: /nas2/checkpoints/janus_dpo_rebuttal/data/iter3/data/images
save_path: /nas2/checkpoints/janus_dpo_rebuttal/data/iter3/data/prompt/step3
save_name: vqa_result_23k_25k

# 앨리스에서 진행
# save_name: vqa_result_18k_21k

# iter2 ckpt
ckpt_path:
model:
  model_path: /nas2/checkpoints/janus_dpo_rebuttal/iter2_hf_ckpt # 7B base
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2

generation_config: 
  do_sample: True
  num_beams: 1
  temperature: 1.2
  top_p: 0.5
  max_new_tokens: 256