# Step 2-2. Image Generation

seed_list: [0,1,2]
world_size: 1
# batch_size: 8 # 16  # attribute, layout
# batch_size: 12  # non-spatial
batch_size: 12    # complex
num_workers: 4

data_path: /nas2/checkpoints/janus_dpo_rebuttal/data/iter3/data/prompt/step2/dense_prompt_14k_end_9000_end.json
s_idx: 0
e_idx: 1000

save_path: /nas2/checkpoints/janus_dpo_rebuttal/data/iter3/data/images
save_name:

# iter1 ckpt
ckpt_path:
model:
  model_path: /nas2/checkpoints/janus_dpo_rebuttal/iter2_hf_ckpt # 7B base
  cache_dir: /nas2/checkpoints/hf_cache_yj
  attn_mode: flash_attention_2


generation_config: 
  parallel_size: 1
  temperature: 1.0
  cfg_weight: 5.0